# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys

class TestExportalandoTest():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_exportalandoTest(self):
    self.driver.get("http://www.learnwebservices.com/locations/server")
    self.driver.set_window_size(1050, 840)
    self.driver.find_element(By.LINK_TEXT, "Edit").click()
    self.driver.find_element(By.ID, "coordsInput").click()
    #self.driver.find_element(By.ID, "coordsInput").send_keys("1.0,5.0")
    #self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
  
